### ISSUE TITLE
add Google Analytics tracking code

### ISSUE THREAD

**Issue by happinessk** [cityofaustin/atxopendata.rocks#15]
- [x]  add Google script 
- [x] send test traffic
- [x] configure data points
